### PR TITLE
Better lightbars.

### PR DESCRIPTION
**Pull request by acmgit**
Makes lightbars fully rotateable.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
Good idea, _but_:

already placed lightbars have a param2 that does not map 1:1 to the facedir rotation:

Before your commit:
screenshot_20240302_174407

Afterwards:
screenshot_20240302_174500

(i had the same idea a while back and already tried this :wink:)

An alternative would be to introduce another _new_ node with `facedir` as param2 (you could even tweak it a bit to look a bit different)

Or:

Write an lbm that migrates the `wallmounted` param2 to the `facedir` param2 on the existing node

**Comment by acmgit** [comment]
At this case, the way with the lbm would be cheapest and fastest.
What happens? I have to turn the bars into a new position .. I use replacer for this ....

Is not a absolutely new case in minetest, after an update of an mod.

**Comment by BuckarooBanzay** [comment]
> What happens? I have to turn the bars into a new position .. I use replacer for this ....
> Is not a absolutely new case in minetest, after an update of an mod.

I would be pretty mad from a builder perspective if i had to redo my work after a mod update (IMO)

**Comment by acmgit** [comment]
Was not the first time, that i've seen this.
On my server i helped, was then a work for half an hour. We worked with the replacer and nobody has checked it ;-).

But now we have fully rotatable lightbars.

**Comment by BuckarooBanzay** [comment]
>  On my server i helped, was then a work for half an hour. We worked with the replacer and nobody has checked it ;-).

Do you volunteer to fix them on all the servers out there using this mod? :smirk:

**Comment by acmgit** [comment]
Of course not ;-).

**Pull request closed without merging**
