### PR TITLE
More slopes and some correction

### PR DESCRIPTION
**Pull request by tanmayameher**
Didn't remember where i changed so the problem happened.
All textures were gone in game and showing the not defined kind of node of scifi.
Although it was showing names on info by pressing F5.
Any way its now all good. So, i am uploading all changed files. See the changes :)

### CODE REVIEW

**Comment by D00Med** [comment]
Thanks again

**Comment by D00Med** [comment]
I have the node builder ready for a table of inputs/outputs, so when I get around to finishing that, there won't be any need for most of the recipes.

**Comment by tanmayameher** [comment]
nice :)
and thanks for making all my work obsolete :P 
lol. kiddin.. :)
oh btw what those "**?**" at the end of each line do in **depends.txt** is that a format which the lua files take in ?!

**Comment by D00Med** [comment]
I might still keep some recipes.
It's to show that the dependency isn't a necessity.
Those dependencies are necessary, but I don't have all those mods(so scifi_nodes won't run) so I made them optional whilst I work on things.

**Comment by tanmayameher** [comment]
ah ok :+1:

**Pull request merged**
