### PR TITLE
Use code from itemframes mod for powered_stand and itemholder

### PR DESCRIPTION
**Pull request by OgelGames**
Fixes issues: https://github.com/pandorabox-io/pandorabox.io/issues/341 and https://github.com/pandorabox-io/pandorabox.io/issues/293

### CODE REVIEW

**Comment by D00Med** [comment]
I don't particularly want to merge this. I thought my way of using the itemholder was quite elegant.

**Comment by OgelGames** [comment]
I agree that your method is much simpler, but the problem is that it uses the default dropped item entity, which means any player (and vacuum tubes) can pick up the item.
By using a custom entity, and using add_entity() instead of add_item(), the only way to pick up the item is by clicking the holder.

**Comment by D00Med** [comment]
I don't really see that as a problem.

**Comment by OgelGames** [comment]
That isn't the only bug fixed with the new code, it's just the one that requires the most additional code; here are the bugs that are fixed with the new code:
- displayed items can be picked up by pipeworks' vacuum tube
- placing and removing an item removes the item's metadata (can be used for instantly repairing tools and armor)
- displayed items can despawn just like dropped items
- the itemholder's protection is only effective one way (items can be removed by any player, but only placed by the owner)
- both the itemholder and powered_stand can be moved by mesecons' pistons and movestones

**Comment by D00Med** [comment]
hmmm, I still would prefer not to change anything

**Comment by SwissalpS** [comment]
> * the itemholder's protection is only effective one way (items can be removed by any player, but only placed by the owner)

I don't mind that, but am not against adding that too for UX concistancy with [itemframes].

**Pull request closed without merging**
