### PR TITLE
Hello DOOMed. Creating some recipe for your mod

### PR DESCRIPTION
**Pull request by tanmayameher**
Hi DOOMed,
I was trying to create some recipes for this mod.

Created currently recipes for **60 nodes**. Will be creating more soon whenever i get some time. :)
I have installed and checked these recipes at least 2 times to make sure there is no recipe collision.
I have tried to make this recipe with very basic mods like homedecor (only for oil and plastic sheet, i think which is default in minetest now), mesecons, moreblocks etc.

Further suggestions are invited :)
Thanks and Regards,
TM

### CODE REVIEW

**Comment by D00Med** [comment]
Thanks for this! I will merge it, but eventually I want to make the 'node builder' create the nodes from materials similar to how the circular saw in moreblocks can make multiple nodes.

**Comment by tanmayameher** [comment]
Welcome :)
ah! i see so the node builder is like a circular saw for scifi mod. You want nodes like stairs, slopes, conical shapes etc right?! or you want every node of scifi will be produced by node builder? Although [unified inventory](https://github.com/minetest-technic/unified_inventory) is used by a lot of servers, which not only show the recipes but also making them with it is quite easy.

**Comment by D00Med** [comment]
Yes, just one node that can build a lot of things from one material.
So a steel ingot could be used to make each color of metal etc. etc.
Oh ok, I might be able to use some of the code from that.

**Comment by tanmayameher** [comment]
ok. yes, just steel ingot for metal block and then some dye according to texture. I tried to comply according to texture esp. because sometimes nodes names don't match with the node's description name or whatever,e.g., scifi_nodes:lighttop actual screen name is metal block lol ;P can't believe it. so, i stick myself to making as per texture and some descriptions. :)

**Comment by D00Med** [comment]
Ok. Haha yeah I'm not good with names

**Pull request merged**
