### PR TITLE
add crafting recipe for teleporter pad

### PR DESCRIPTION
**Pull request by ncorder**
**Description**: add crafting recipe for teleporter pad

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
Nice work :+1: 

But: afaik the teleport pads only work very rudimentary (only 2 connect to each other) and this only in a singleplayer session (without disconnects)
I imagine that they are pretty useless and buggy in multiplayer...

Would it be an option to add a setting for the recipe or do you have other ideas?

**Comment by ncorder** [comment]
> Nice work +1
> 
> But: afaik the teleport pads only work very rudimentary (only 2 connect to each other) and this only in a singleplayer session (without disconnects)
> I imagine that they are pretty useless and buggy in multiplayer...

As far as I am aware, the [Blocky Survival](https://github.com/BlockySurvival) Server does have the teleporters functioning with the Scifi_Node mod. However, they do not have a recipe for them either, so it might be they have them loaded or something else.

> Would it be an option to add a setting for the recipe or do you have other ideas?

I am a bit new to Minetest programming, but I thought this would be a good PR to try and get into the platform and how they function. I know on some servers they have different recipes or kind of overrode the usual crafting recipe, but I understand that.

Is there a different folder or config file I should be looking at to make it an optional setup.

**Comment by ncorder** [comment]
My understanding is that the teleporters have a limit of 2 per server right now I believe as well. 
That might be something I could look into fixing to 2 per player or another setup.
______________________________

I didn't notice this until I posted the PR and it was brought to my attention. Was that the issue you were trying to point out to me?

**Comment by BuckarooBanzay** [comment]
I took the liberty and added your commit in a new PR here #61
It also includes a setting to enable the recipe: https://github.com/D00Med/scifi_nodes/pull/61/commits/e0e3a306fb8835f639bfc4791b57abff49a1402c

> My understanding is that the teleporters have a limit of 2 per server right now I believe as well.
That might be something I could look into fixing to 2 per player or another setup.

Judging from the code and the crashes i've seen i don't think they are usable outside of a singeplayer environment (yet) :confounded: 
Feel free to provide a fix if you want :wink: 

Let me know if that works for you

**Comment by ncorder** [comment]
> I took the liberty and added your commit in a new PR here #61 It also includes a setting to enable the recipe: [e0e3a30](https://github.com/D00Med/scifi_nodes/commit/e0e3a306fb8835f639bfc4791b57abff49a1402c)
> 
> > My understanding is that the teleporters have a limit of 2 per server right now I believe as well.
> > That might be something I could look into fixing to 2 per player or another setup.
> 
> Judging from the code and the crashes i've seen i don't think they are usable outside of a singeplayer environment (yet) confounded Feel free to provide a fix if you want wink
> 
> Let me know if that works for you

That's awesome and works great, thanks you so much for reviewing my PR.

**Pull request closed without merging**
